const $=id=>document.getElementById(id), esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const names={lessons:'教材与微课',questions:'高考题库',resources:'我的资料',practice:'收藏与练习',audit:'资料审计'};
let C,Q,R,A,view='lessons',book='',page=0,current=null,timerStart=null,elapsed=0,timerTarget=null;
function readStore(){try{let x=JSON.parse(localStorage.getItem('geo-classroom-practice-v1'));if(x&&Array.isArray(x.favorites)&&Array.isArray(x.sessions))return x;}catch{}return{favorites:[],sessions:[]};}
let personal=readStore();
function persist(){try{localStorage.setItem('geo-classroom-practice-v1',JSON.stringify(personal));}catch{toast('浏览器存储不可用，请导出备份');}}
function toast(s){$('toast').textContent=s;$('toast').style.display='block';clearTimeout(toast.t);toast.t=setTimeout(()=>$('toast').style.display='none',2600);}
function favorite(id){personal.favorites=personal.favorites.includes(id)?personal.favorites.filter(x=>x!==id):[...personal.favorites,id];persist();document.querySelectorAll(`[data-fav="${id}"]`).forEach(b=>b.textContent=personal.favorites.includes(id)?'★ 已收藏':'☆ 收藏');if(view==='practice')render();}
function favoriteButton(id){return `<button data-fav="${id}">${personal.favorites.includes(id)?'★ 已收藏':'☆ 收藏'}</button>`;}
function sourceLink(s){let r=R.find(x=>x.id===s.resourceId);return `<a target="_blank" rel="noopener" href="./view/${s.resourceId}.html${s.paragraphStart?'#p'+s.paragraphStart:''}">${esc(r?.name||s.resourceId)}</a>${s.paragraphStart?` · 原件段落 ${s.paragraphStart}–${s.paragraphEnd}`:''}`;}
function list(items){return '<ul>'+items.map(x=>'<li>'+esc(x)+'</li>').join('')+'</ul>';}
function setView(v){view=v;page=0;document.querySelectorAll('#nav button').forEach(b=>b.classList.toggle('active',b.dataset.view===v));$('view-title').textContent=names[v];$('crumb').textContent='备课工作台 / '+names[v];$('subtitle').textContent={lessons:'按教材顺序，建立自己的试讲路线。',questions:'原题与解析可追溯；机器切分题组需对照原件。',resources:'147份资料，保留路径、版本与提取状态。',practice:'收藏和练习记录保存在当前浏览器，可导出备份。',audit:'了解已有资料、重复关系与尚待完成的内容。'}[v];['year','region','qtype'].forEach(id=>$(id).hidden=v!=='questions');['stage','stars'].forEach(id=>$(id).hidden=v!=='lessons');$('ready').parentElement.hidden=v!=='lessons';render();}
function filteredTopics(){let term=$('search').value.trim().toLowerCase();return C.topics.filter(t=>(!book||t.bookId===book)&&(!$('stage').value||t.stage===$('stage').value)&&t.stars>=+$('stars').value&&(!$('ready').checked||t.lesson)&&(!term||JSON.stringify(t).toLowerCase().includes(term)));}
function card(t){return `<button class="card" data-topic="${t.id}"><div class="card-top"><span>${'★'.repeat(t.stars)}</span><span class="badge ${t.lesson?'':'pending'}">${t.lesson?'示范稿':'待编写'}</span></div><h3>${esc(t.title)}</h3><p>${esc(t.lesson?.focus||t.chapter)}</p><div class="card-bottom"><span>${t.stage} · ${esc(t.book)}</span><span>${t.lesson?'12分钟 · 读图试讲 ↗':'目录入口 →'}</span></div></button>`;}
function render(){let html='',term=$('search').value.trim().toLowerCase();
 if(view==='lessons'){
  const ts=filteredTopics();let chosen=C.books.find(b=>b.id===book);
  html=`<div class="notice">已建 128 个课节入口，8 节示范稿；其余待编写。教材目录保留版次核验状态。${chosen?` <a href="${chosen.source}" target="_blank" rel="noopener">${esc(chosen.edition)} · 目录依据</a>`:''}</div>`;
  for(const b of C.books){const bt=ts.filter(t=>t.bookId===b.id);if(!bt.length)continue;html+=`<h3 class="chapter">${esc(b.title)} <small class="text-muted">${bt.length} 个课节</small></h3><div class="cards">${bt.map(card).join('')}</div>`;}
  if(!ts.length)html+='<div class="empty">没有符合条件的课节，请尝试清除筛选。</div>';
 }else if(view==='questions'){
  let qs=Q.filter(q=>(!$('year').value||String(q.year)===$('year').value)&&(!$('region').value||q.region===$('region').value)&&(!$('qtype').value||q.type===$('qtype').value)&&(!term||JSON.stringify(q).toLowerCase().includes(term)));
  html=`<div class="notice">${qs.length} 个候选题组。不是已校核题数；来源年份按独立卷文件标注，难度待评定，考点为关键词候选。图表与公式请打开来源预览对照。</div>`+qs.slice(page*20,page*20+20).map(q=>`<article class="list-item"><div class="row"><span class="badge">${q.year||'年份待核'} · ${esc(q.region||'卷别待核')}</span><span class="text-muted">${q.type} · 难度待评定</span></div><h3>第 ${esc(q.numbers)} 题 · ${esc(q.text.slice(0,72))}…</h3><p>${esc(q.status)}</p><div class="row"><button data-question="${q.id}">查看题目与解析 →</button>${favoriteButton(q.id)}</div></article>`).join('')+pager(qs.length);
 }else if(view==='resources'){
  const rs=R.filter(r=>!term||JSON.stringify(r).toLowerCase().includes(term));html=`<div class="notice">${rs.length} 份来源记录；完全相同的文件保留来源，并标注主记录。旧版DOC与扫描正文尚待转换/OCR。</div>`+rs.slice(page*25,page*25+25).map(r=>`<article class="list-item"><span class="badge">${esc(r.ext)} · ${esc(r.category)}</span><h3>${esc(r.name)}</h3><p>${esc(r.status)} · ${(r.size/1024/1024).toFixed(2)} MB ${r.canonicalId!==r.id?' · 重复，主记录 '+r.canonicalId:''}</p><p>${esc(r.path)}${r.member?' → '+esc(r.member):''}</p><div class="row"><button data-resource="${r.id}">查看来源与文本</button><a href="./view/${r.id}.html" target="_blank" rel="noopener">打开来源预览</a></div></article>`).join('')+pager(rs.length,25);
 }else if(view==='practice'){
  const ts=C.topics.filter(t=>personal.favorites.includes(t.id));const qs=Q.filter(q=>personal.favorites.includes(q.id));html=`<div class="row"><button id="export">导出收藏与练习记录</button><button id="import">导入备份</button><input type="file" id="import-file" accept="application/json" hidden></div><h3>我的收藏 · ${ts.length+qs.length}</h3><div class="cards">${ts.map(card).join('')}</div>`+qs.map(q=>`<div class="list-item"><button data-question="${q.id}">${q.year} ${esc(q.region)} 第${esc(q.numbers)}题</button> ${favoriteButton(q.id)}</div>`).join('')+(ts.length+qs.length?'':'<div class="empty">打开微课或题目，点击收藏，即可在这里找到。</div>')+'<h3>练习记录</h3>'+personal.sessions.slice().reverse().map(s=>`<div class="list-item"><h3>${esc(C.topics.find(t=>t.id===s.topicId)?.title||s.topicId)}</h3><p>${esc(s.date)} · ${(s.seconds/60).toFixed(1)} 分钟 · 自评 ${esc(s.rating)}/5</p><p>${esc(s.note||'未填写复盘笔记')}</p></div>`).join('');
 }else{
  html=`<div class="notice">已完成全量文件级审计；正文提取不等于逐页视觉审校。全库微课内容仍在建设中。</div><div class="detail-grid"><div class="box"><h3>资料组成</h3><table>${Object.entries(A.extensions).map(([k,v])=>`<tr><td>${k}</td><td>${v}份</td></tr>`).join('')}</table><p>147份资料 · 144份不同二进制内容</p></div><div class="box"><h3>提取情况</h3>${list(Object.entries(A.statuses).map(([k,v])=>k+'：'+v+'份'))}</div></div><div class="box"><h3>完全重复项</h3>${A.duplicateGroups.map(g=>`<p>${g.map(id=>`<button data-resource="${id}">${id}</button>`).join(' ↔ ')}</p>`).join('')}</div><div class="box"><h3>内容与版本注意事项</h3>${list(['未发现PPT/PPTX或独立教材；不能直接生成全套现成课件。','五份疑似合订资料单独标记，未把文件名年份分配到全部题。','淮安模拟题16页版和8页版关联保留；不是完全重复文件。','教学设计含东南亚与人口分布两篇，已作为改编示范来源。','初中目录参考新修订网络目录，待核对实际教材版权页；跨学科活动节点待补。','533个自动切分题组需逐题检查图像、公式、题干边界与答案；未完成难度评定。','收藏和练习保存在浏览器本地，不会自动同步到其他设备。'])}</div>`;
 }
 $('content').innerHTML=html;
 $('books').innerHTML=C.books.map(b=>`<button data-book="${b.id}" class="${book===b.id?'selected':''}">${esc(b.title)}</button>`).join('');
}
function pager(n,size=20){return n>size?`<div class="pager"><button data-page="${page-1}" ${page===0?'disabled':''}>上一页</button><span>${page+1} / ${Math.ceil(n/size)}</span><button data-page="${page+1}" ${(page+1)*size>=n?'disabled':''}>下一页</button></div>`:'';}
function modal(title,body){$('detail-label').textContent=title;$('detail-body').innerHTML=body;if(!$('detail').open)$('detail').showModal();$('detail').scrollTop=0;}
function topic(id){current=id;const t=C.topics.find(x=>x.id===id),l=t.lesson,b=C.books.find(x=>x.id===t.bookId);let html=`<span class="badge">${esc(t.book)} / ${esc(t.chapter)}</span><h2 class="lesson-title">${esc(t.title)}</h2><div class="row">${favoriteButton(id)}<a href="${b.source}" target="_blank" rel="noopener">教材目录依据</a></div>`;
 if(!l){modal('课节入口',html+'<div class="notice">此课节尚未编写精品试讲稿，当前仅完成目录建档。</div><p>将包含：10—15分钟试讲、目标、情境、问题链、PPT建议、板书、易错点与面试亮点。</p>'+related(id));return;}
 html+=`<div class="notice">${esc(l.status)}。这是分段讲稿与活动安排，不是全程连续朗读稿；时长须结合读图、板书和实际语速验证。</div><h3>${esc(l.focus)}</h3><div class="box"><h3>试讲练习</h3><div class="timer"><strong id="clock">${timerTarget===id?timeText(): '00:00'}</strong><button id="start-timer" data-id="${id}">开始 / 暂停</button><button id="reset-timer">重新计时</button></div><textarea id="note" placeholder="复盘：哪一步讲清楚了？哪一步需要改进？" aria-label="复盘笔记"></textarea><div class="row"><label>自评 <select id="rating"><option>3</option><option>1</option><option>2</option><option>4</option><option>5</option></select> / 5</label><button id="save-practice" data-id="${id}">保存本次练习</button></div></div><div class="detail-grid"><div class="box"><h3>教学目标</h3>${list(l.objectives)}</div><div class="box"><h3>问题链</h3>${list(l.questionChain)}</div></div><h3>12分钟试讲安排</h3>`;
 html+=l.segments.map(s=>`<section class="segment"><h3><span class="badge">${s.time}</span> ${esc(s.label)}</h3><p>${esc(s.script)}</p><small>活动与节奏：${esc(s.action)}</small></section>`).join('');
 html+=`<div class="detail-grid"><div class="box"><h3>PPT建议</h3>${list(l.ppt)}</div><div class="box"><h3>易错点</h3>${list(l.misconceptions)}</div></div><h3>板书设计</h3><div class="board">${esc(l.board)}</div><div class="box"><h3>面试亮点</h3>${list(l.highlights)}</div><div class="box resource-link"><h3>内容来源</h3>${typeof l.source==='string'?esc(l.source):sourceLink(l.source)+' · PDF第'+l.source.pages+'页<p>'+esc(l.source.note)+'</p>'}</div>`+related(id);modal('精品微课 · 示范稿',html);
}
function related(id){const qs=Q.filter(q=>q.topicIds.includes(id));return `<h3>关联高考题 · ${qs.length} 组候选</h3><p class="text-muted">关键词推荐，考点匹配待审定；点击可查题目、解析及原件。</p>`+qs.slice(0,8).map(q=>`<div class="list-item"><button data-question="${q.id}">${q.year} ${esc(q.region)} · 第${esc(q.numbers)}题 →</button><p>${esc(q.text.slice(0,95))}…</p></div>`).join('')+(!qs.length?'<p>暂无匹配题组，尚未完成此知识点配题。</p>':'');}
function question(id){const q=Q.find(x=>x.id===id);modal('题目档案',`<span class="badge">${esc(q.examType)}</span><h2>${q.year} · ${esc(q.region)} · 第 ${esc(q.numbers)} 题</h2><div class="row">${favoriteButton(id)}<span>${q.type} · 难度：${q.difficulty}</span></div><div class="notice">${esc(q.status)}。纯文本可能缺图或公式，不建议脱离原件直接用于授课。</div><div class="question-text">${esc(q.text)}</div><details><summary>展开答案与解析</summary><div class="box question-text"><strong>原文件答案</strong><p>${esc(q.answer)}</p><strong>原文件解析（自动提取）</strong><p>${esc(q.explanation)}</p></div></details><div class="box resource-link"><h3>来源与位置</h3>${q.sources.map(sourceLink).join('<br>')}<p>难度依据：${esc(q.difficultyBasis)}</p><p>候选考点：${q.topicIds.map(id=>esc(C.topics.find(t=>t.id===id)?.title||id)).join('、')||'待标注'}</p></div><p>打开上方来源链接，可查看题图。源文件预览会定位至相应段落。</p>`);}
async function resource(id){const r=await fetch('./resources/'+id+'.json').then(x=>x.json());modal('来源档案',`<h2>${esc(r.name)}</h2><div class="notice">${esc(r.status)}</div><div class="box resource-link"><p>原始路径：${esc(r.path)}</p><p>ZIP成员：${esc(r.member||'非压缩包成员')}</p><p>SHA-256：${esc(r.sha256)}</p><p>主记录：${r.canonicalId} · 正文字数 ${r.textLength}</p><p>${esc(r.metadataNote||'')}</p><a target="_blank" rel="noopener" href="./view/${id}.html">打开来源预览 →</a></div><details><summary>查看提取文本（最多前12000字）</summary><div class="question-text">${esc([...r.paragraphs,...r.pages].join('\n').slice(0,12000)||'尚无可用正文')}</div></details>`);}
function totalSeconds(){return elapsed+(timerStart?Math.floor((Date.now()-timerStart)/1000):0);}
function timeText(){let n=totalSeconds();return `${String(Math.floor(n/60)).padStart(2,'0')}:${String(n%60).padStart(2,'0')}`;}
setInterval(()=>{if($('clock')&&current===timerTarget)$('clock').textContent=timeText();},500);
function backup(){const blob=new Blob([JSON.stringify(personal,null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='山海课间-练习备份.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
document.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;const d=b.dataset;
 if(d.view){setView(d.view);return;}if(d.book){book=d.book;$('stage').value='';$('search').value='';setView('lessons');return;}if(d.topic){topic(d.topic);return;}if(d.question){question(d.question);return;}if(d.fav){favorite(d.fav);return;}if(d.resource){resource(d.resource).catch(()=>toast('资料暂时无法读取'));return;}if(d.page!==undefined){page=+d.page;render();return;}
 if(b.id==='close')$('detail').close();
 if(b.id==='reset'){book='';['search','stage','year','region','qtype'].forEach(id=>$(id).value='');$('stars').value='0';$('ready').checked=false;page=0;render();}
 if(b.id==='random'){const pool=filteredTopics().filter(t=>t.lesson);if(!pool.length){toast('当前筛选没有可练习的示范稿');return;}topic(pool[Math.floor(Math.random()*pool.length)].id);toast('已从当前筛选中的示范稿随机抽取');}
 if(b.id==='start-timer'){if(timerTarget!==d.id){timerTarget=d.id;elapsed=0;timerStart=null;}if(timerStart){elapsed=totalSeconds();timerStart=null;toast('已暂停计时');}else{timerStart=Date.now();toast('已开始计时');}}
 if(b.id==='reset-timer'){elapsed=0;timerStart=null;timerTarget=current;$('clock').textContent='00:00';}
 if(b.id==='save-practice'){if(timerTarget!==d.id||totalSeconds()<1){toast('请先开始试讲计时');return;}const secs=totalSeconds();personal.sessions.push({topicId:d.id,date:new Date().toLocaleString('zh-CN'),seconds:secs,rating:+$('rating').value,note:$('note').value});persist();elapsed=secs;timerStart=null;toast('本次练习已保存');}
 if(b.id==='export')backup();if(b.id==='import')$('import-file').click();
});
document.addEventListener('change',async e=>{if(e.target.id==='import-file'){try{const f=e.target.files[0];if(!f||f.size>5e6)throw Error();const x=JSON.parse(await f.text());const valid=new Set([...C.topics,...Q].map(x=>x.id));if(!Array.isArray(x.favorites)||!x.favorites.every(id=>typeof id==='string'&&valid.has(id))||!Array.isArray(x.sessions)||!x.sessions.every(s=>C.topics.some(t=>t.id===s.topicId)&&Number.isFinite(s.seconds)&&s.seconds>=0&&s.seconds<86400&&typeof s.date==='string'&&typeof s.note==='string'&&Number.isInteger(s.rating)&&s.rating>=1&&s.rating<=5))throw Error();personal={favorites:[...new Set([...personal.favorites,...x.favorites])],sessions:[...personal.sessions,...x.sessions]};persist();render();toast('备份已合并导入');}catch{toast('备份格式不正确，未修改现有记录');}}});
['search','stage','stars','ready','year','region','qtype'].forEach(id=>$(id).addEventListener(id==='search'?'input':'change',()=>{page=0;render();}));
Promise.all(['./data/catalog.json','./data/questions.json','./data/resources.json','./data/audit.json'].map(url=>fetch(url).then(r=>{if(!r.ok)throw Error(url);return r.json();}))).then(([c,q,r,a])=>{C=c;Q=q;R=r;A=a;$('stats').innerHTML=[[C.books.length,'册教材目录'],[C.topics.filter(t=>t.lesson).length,'节示范试讲'],[Q.length,'组待校核题组'],[R.length,'份资料']].map(([n,s])=>`<div class="stat"><strong>${n}</strong><span>${s}</span></div>`).join('');$('year').innerHTML+=[...new Set(Q.map(q=>q.year).filter(Boolean))].sort().reverse().map(x=>`<option>${x}</option>`).join('');$('region').innerHTML+=[...new Set(Q.map(q=>q.region).filter(Boolean))].sort().map(x=>`<option>${esc(x)}</option>`).join('');setView('lessons');}).catch(()=>{$('content').innerHTML='<div class="notice">无法读取资料，请确认本地服务正在运行，并刷新页面。</div>';});
