/* Page annotations attach to content blocks, independent of scrolling. */
(()=>{'use strict';
const canvas=document.createElement('canvas');canvas.className='ink-canvas';canvas.setAttribute('aria-label','当前页面手写标注层');
const bar=document.createElement('div');bar.className='ink-toolbar';bar.innerHTML='<button data-ink="browse" class="active">浏览</button><button data-ink="pen">笔</button><button data-ink="highlight">荧光</button><button data-ink="erase">橡皮</button><input id="ink-color" type="color" value="#ba3a45" aria-label="笔颜色"><select id="ink-width" aria-label="笔宽"><option value="2">细</option><option value="4" selected>中</option><option value="7">粗</option></select><button id="ink-undo">撤销</button><button id="ink-redo">重做</button><details><summary>备份</summary><div class="ink-menu"><label><input id="ink-touch" type="checkbox"> 允许手指书写</label><button id="ink-export">导出全部笔迹</button><button id="ink-import">导入笔迹</button><input id="ink-file" type="file" accept="application/json,.json" hidden></div></details><div class="ink-status" role="status">浏览可滚动；选择笔后用 Pencil 书写，默认忽略手指触碰。</div>';
document.body.append(canvas,bar);const ctx=canvas.getContext('2d'),status=t=>bar.querySelector('.ink-status').textContent=t;
let db,tool='browse',key='',strokes=[],redo=[],undo=[],active=null,previous=[],dirty=new Map(),writeChain=Promise.resolve(),epoch=0,frame=0,loading=true;
const ready=new Promise((resolve,reject)=>{const r=indexedDB.open('geo-page-notes-v3',1);r.onupgradeneeded=()=>r.result.createObjectStore('pages');r.onsuccess=()=>{db=r.result;resolve();};r.onerror=()=>reject(r.error);});ready.catch(()=>status('笔迹存储不可用，请用导出备份保存当前笔迹。'));
async function get(k){await ready;return new Promise((res,rej)=>{const r=db.transaction('pages').objectStore('pages').get(k);r.onsuccess=()=>res(r.result||[]);r.onerror=()=>rej(r.error);});}
async function put(k,v){await ready;return new Promise((res,rej)=>{const t=db.transaction('pages','readwrite');t.objectStore('pages').put(v,k);t.oncomplete=res;t.onerror=()=>rej(t.error);t.onabort=()=>rej(t.error);});}
function save(){const k=key,v=structuredClone(strokes);dirty.set(k,v);status('正在保存笔迹…');writeChain=writeChain.catch(()=>{}).then(()=>put(k,v)).then(()=>{if(dirty.get(k)===v)dirty.delete(k);status('笔迹已保存在本设备；换设备前请导出备份。');}).catch(()=>status('保存失败，笔迹暂存在内存；请立即导出备份。'));}
function anchors(){document.querySelectorAll('#content [data-topic]').forEach(el=>{if(!el.dataset.noteAnchor)el.dataset.noteAnchor='topic-'+el.dataset.topic;});document.querySelectorAll('#content>*,#detail-body>*').forEach((el,i)=>{if(!el.dataset.noteAnchor)el.dataset.noteAnchor='block-'+i;});}
function rect(id){if(id==='document')return {left:-scrollX,top:-scrollY,width:document.documentElement.clientWidth};const e=document.querySelector('[data-note-anchor="'+CSS.escape(id)+'"]');if(!e||!e.getClientRects().length)return null;return e.getBoundingClientRect();}
function anchorAt(x,y){canvas.style.pointerEvents='none';const e=document.elementFromPoint(x,y)?.closest('[data-note-anchor]');canvas.style.pointerEvents=tool==='browse'?'none':'auto';return e?.dataset.noteAnchor||'document';}
function draw(){frame=0;ctx.setTransform(devicePixelRatio,0,0,devicePixelRatio,0,0);ctx.clearRect(0,0,innerWidth,innerHeight);for(const s of [...strokes,...(active?[active]:[])]){const r=rect(s.anchor);if(!r)continue;ctx.save();ctx.strokeStyle=s.color;ctx.fillStyle=s.color;ctx.globalAlpha=s.tool==='highlight'?.25:1;ctx.lineJoin=ctx.lineCap='round';const ps=s.points;if(ps.length===1){ctx.beginPath();ctx.arc(r.left+ps[0].x*r.width,r.top+ps[0].y*r.width,s.width/2,0,Math.PI*2);ctx.fill();}else for(let i=1;i<ps.length;i++){ctx.lineWidth=s.width*(s.tool==='highlight'?5:(.6+.8*ps[i].p));ctx.beginPath();ctx.moveTo(r.left+ps[i-1].x*r.width,r.top+ps[i-1].y*r.width);ctx.lineTo(r.left+ps[i].x*r.width,r.top+ps[i].y*r.width);ctx.stroke();}ctx.restore();}}
function paint(){if(!frame)frame=requestAnimationFrame(draw);}function resize(){canvas.width=Math.round(innerWidth*devicePixelRatio);canvas.height=Math.round(innerHeight*devicePixelRatio);paint();}
async function route(){const next=(document.getElementById('detail').open?'dialog:'+document.getElementById('detail-label').textContent+':'+document.getElementById('detail-body').textContent.slice(0,140):document.body.dataset.inkKey||'view:lessons');anchors();if(next===key){paint();return;}if(active)finish();key=next;const n=++epoch;loading=true;strokes=[];redo=[];undo=[];paint();try{const value=dirty.has(next)?dirty.get(next):await get(next);if(n===epoch)strokes=structuredClone(value);}catch{status('无法读取本设备笔迹；仍可书写并导出备份。');}finally{if(n===epoch){loading=false;paint();}}}
function point(e){const r=rect(active.anchor);if(r)active.points.push({x:(e.clientX-r.left)/r.width,y:(e.clientY-r.top)/r.width,p:e.pressure||.5});}
function eraseAt(e){strokes=strokes.filter(s=>{const r=rect(s.anchor);if(!r)return true;return !s.points.some((p,i)=>{const a={x:r.left+p.x*r.width,y:r.top+p.y*r.width},q=s.points[Math.max(0,i-1)],b={x:r.left+q.x*r.width,y:r.top+q.y*r.width};const dx=a.x-b.x,dy=a.y-b.y,t=Math.max(0,Math.min(1,((e.clientX-b.x)*dx+(e.clientY-b.y)*dy)/(dx*dx+dy*dy||1)));return Math.hypot(e.clientX-b.x-t*dx,e.clientY-b.y-t*dy)<14+s.width;});});}
let drawing=false,pointer=null;
canvas.addEventListener('pointerdown',e=>{if(tool==='browse'||loading||drawing||e.pointerType==='touch'&&!bar.querySelector('#ink-touch').checked)return;e.preventDefault();drawing=true;pointer=e.pointerId;canvas.setPointerCapture(e.pointerId);previous=structuredClone(strokes);if(tool==='erase')eraseAt(e);else{active={id:crypto.randomUUID(),anchor:anchorAt(e.clientX,e.clientY),tool,color:bar.querySelector('#ink-color').value,width:+bar.querySelector('#ink-width').value,points:[]};point(e);}paint();});
canvas.addEventListener('pointermove',e=>{if(!drawing||e.pointerId!==pointer)return;e.preventDefault();if(tool==='erase')eraseAt(e);else{const ps=e.getCoalescedEvents?.();for(const p of ps?.length?ps:[e])point(p);}paint();});
function finish(){if(!drawing)return;if(active){strokes.push(active);active=null;}undo.push(previous);if(undo.length>60)undo.shift();redo=[];drawing=false;pointer=null;save();paint();}
canvas.addEventListener('pointerup',finish);canvas.addEventListener('pointercancel',finish);canvas.addEventListener('lostpointercapture',finish);
bar.addEventListener('click',e=>{const b=e.target.closest('[data-ink]');if(b){finish();tool=b.dataset.ink;canvas.style.pointerEvents=tool==='browse'?'none':'auto';bar.querySelectorAll('[data-ink]').forEach(x=>x.classList.toggle('active',x===b));status(tool==='browse'?'浏览模式：可以滚动、点击与切换课程。':'直接在页面书写；需要滚动或点击时切回“浏览”。');}if(e.target.id==='ink-undo'&&undo.length){redo.push(structuredClone(strokes));strokes=undo.pop();save();paint();}if(e.target.id==='ink-redo'&&redo.length){undo.push(structuredClone(strokes));strokes=redo.pop();save();paint();}if(e.target.id==='ink-import')bar.querySelector('#ink-file').click();if(e.target.id==='ink-export')exportNotes();});
async function all(){await ready;return new Promise((res,rej)=>{const out={},r=db.transaction('pages').objectStore('pages').openCursor();r.onsuccess=()=>{const c=r.result;if(c){out[c.key]=c.value;c.continue();}else res(out);};r.onerror=()=>rej(r.error);});}
async function exportNotes(){await writeChain;let pages={};try{pages=await all();}catch{}for(const [k,v] of dirty)pages[k]=v;pages[key]=strokes;const u=URL.createObjectURL(new Blob([JSON.stringify({format:'geo-page-notes-v3',pages})],{type:'application/json'})),a=document.createElement('a');a.href=u;a.download='山海课间-整页笔迹.json';a.click();setTimeout(()=>URL.revokeObjectURL(u),1000);}
function valid(s){return s&&typeof s.id==='string'&&s.id.length<100&&typeof s.anchor==='string'&&s.anchor.length<250&&['pen','highlight'].includes(s.tool)&&/^#[0-9a-f]{6}$/i.test(s.color)&&[2,4,7].includes(s.width)&&Array.isArray(s.points)&&s.points.length>0&&s.points.length<100000&&s.points.every(p=>['x','y','p'].every(k=>Number.isFinite(p[k]))&&Math.abs(p.x)<10000&&Math.abs(p.y)<10000&&p.p>=0&&p.p<=1);}
bar.querySelector('#ink-file').addEventListener('change',async e=>{try{const f=e.target.files[0];if(!f)return;if(f.size>30e6)throw Error('备份过大');const x=JSON.parse(await f.text());if(x.format!=='geo-page-notes-v3'||!x.pages||typeof x.pages!=='object'||Array.isArray(x.pages)||!Object.entries(x.pages).every(([k,v])=>k.length<500&&Array.isArray(v)&&v.length<10000&&v.every(valid)))throw Error('格式不正确');await writeChain;for(const [k,v]of Object.entries(x.pages)){let old=dirty.get(k);if(!old)old=await get(k);const map=new Map(old.map(s=>[s.id,s]));for(const s of v)if(!map.has(s.id))map.set(s.id,s);const merged=[...map.values()];dirty.set(k,merged);await put(k,merged);dirty.delete(k);if(k===key)strokes=merged;}undo=[];redo=[];paint();status('备份已合并；相同笔迹不会重复导入。');}catch(e){status('导入未完成：'+e.message+'。现有笔迹保留。');}finally{e.target.value='';}});
const dialog=document.getElementById('detail');new MutationObserver(()=>{const host=dialog.open?dialog:document.body;host.append(canvas,bar);route();}).observe(dialog,{attributes:true,attributeFilter:['open']});
new MutationObserver(route).observe(document.body,{attributes:true,attributeFilter:['data-ink-key']});new MutationObserver(()=>{anchors();paint();}).observe(document.getElementById('content'),{childList:true,subtree:true});
document.addEventListener('geo-content-ready',()=>{anchors();paint();});window.addEventListener('scroll',paint,true);window.addEventListener('resize',resize);resize();route();
})();
