const $=id=>document.getElementById(id), paper=$('paper'),ink=$('ink'),ctx=paper.getContext('2d'),ic=ink.getContext('2d');
const params=new URLSearchParams(location.search),topicId=params.get('topic'),bookKey='book:'+(params.get('book')||'default');let lesson,mode='slides',page=0,docKey='',pdf=null,strokes=[],redo=[],history=[],active=null,tool='pen',drawing=false,renderEpoch=0,saveChain=Promise.resolve(),db,busy=false;
const pendingInk=new Map();
function status(s){$('status').textContent=s;}
const ready=new Promise((resolve,reject)=>{const r=indexedDB.open('geo-notebook-v1',1);r.onupgradeneeded=()=>{r.result.createObjectStore('ink');r.result.createObjectStore('docs');};r.onsuccess=()=>{db=r.result;resolve();};r.onerror=()=>reject(r.error);});
async function read(store,key){await ready;return new Promise((resolve,reject)=>{const r=db.transaction(store).objectStore(store).get(key);r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error);});}
async function write(store,key,value){await ready;return new Promise((resolve,reject)=>{const tx=db.transaction(store,'readwrite');tx.objectStore(store).put(value,key);tx.oncomplete=resolve;tx.onerror=()=>reject(tx.error);tx.onabort=()=>reject(tx.error);});}
function key(){return docKey+':'+mode+':'+page;}
function save(){const k=key(),value=structuredClone(strokes);pendingInk.set(k,value);status('保存中…');saveChain=saveChain.catch(()=>{}).then(()=>write('ink',k,value)).then(()=>status('笔迹已保存在本设备')).catch(()=>{status('保存失败，请立即导出笔迹备份');});return saveChain;}
function download(blob,name){const u=URL.createObjectURL(blob),a=document.createElement('a');a.href=u;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(u),30000);}
function lineText(text,x,y,maxWidth,font=30,color='#183f34',line=48){ctx.font=`${font}px system-ui,"Microsoft YaHei",sans-serif`;ctx.fillStyle=color;let buf='';for(const c of text){if(c==='\n'||ctx.measureText(buf+c).width>maxWidth){ctx.fillText(buf,x,y);y+=line;buf=c==='\n'?'':c;}else buf+=c;}if(buf){ctx.fillText(buf,x,y);y+=line;}return y;}
function paintStroke(s){ic.save();ic.strokeStyle=s.color;ic.fillStyle=s.color;ic.globalAlpha=s.tool==='highlight'?.24:1;ic.lineCap='round';ic.lineJoin='round';const pts=s.points;if(pts.length===1){ic.beginPath();ic.arc(pts[0].x*ink.width,pts[0].y*ink.height,s.width/2,0,Math.PI*2);ic.fill();}for(let i=1;i<pts.length;i++){ic.lineWidth=s.width*(s.tool==='highlight'?5:(.6+pts[i].p*.8));ic.beginPath();ic.moveTo(pts[i-1].x*ink.width,pts[i-1].y*ink.height);ic.lineTo(pts[i].x*ink.width,pts[i].y*ink.height);ic.stroke();}ic.restore();}
function repaint(){ic.clearRect(0,0,ink.width,ink.height);strokes.forEach(paintStroke);if(active)paintStroke(active);$('undo').disabled=!strokes.length&&!history.length;$('redo').disabled=!redo.length;}
function point(e){const r=ink.getBoundingClientRect();return{x:Math.max(0,Math.min(1,(e.clientX-r.left)/r.width)),y:Math.max(0,Math.min(1,(e.clientY-r.top)/r.height)),p:e.pressure||.5};}
function erase(p){const d2=(a,b)=>(a.x-b.x)**2+(a.y-b.y)**2;strokes=strokes.filter(s=>!s.points.some((q,i)=>{if(d2(q,p)<.0005)return true;if(!i)return false;const a=s.points[i-1],dx=q.x-a.x,dy=q.y-a.y,l=dx*dx+dy*dy,t=l?Math.max(0,Math.min(1,((p.x-a.x)*dx+(p.y-a.y)*dy)/l)):0;return d2(p,{x:a.x+t*dx,y:a.y+t*dy})<.0005;}));repaint();}
ink.addEventListener('pointerdown',e=>{if(busy||drawing||tool==='browse'||(e.pointerType==='touch'&&!$('finger').checked))return;e.preventDefault();ink.setPointerCapture(e.pointerId);drawing=e.pointerId;history.push(structuredClone(strokes));redo=[];if(tool==='eraser')erase(point(e));else{active={tool,color:$('color').value,width:+$('width').value,points:[point(e)]};repaint();}});
ink.addEventListener('pointermove',e=>{if(drawing!==e.pointerId)return;e.preventDefault();if(tool==='eraser')erase(point(e));else{const qs=e.getCoalescedEvents?.();for(const q of qs?.length?qs:[e])active.points.push(point(q));repaint();}});
function finish(e){if(drawing!==e.pointerId)return;if(active){strokes.push(active);active=null;}drawing=false;repaint();save();}
ink.addEventListener('pointerup',finish);ink.addEventListener('pointercancel',finish);
function setTool(t){tool=t;ink.classList.toggle('browse',t==='browse');['browse','pen','highlight','eraser'].forEach(x=>$(x).setAttribute('aria-pressed',String(x===t)));}
['browse','pen','highlight','eraser'].forEach(x=>$(x).onclick=()=>setTool(x));
$('undo').onclick=()=>{if(history.length||strokes.length){redo.push(structuredClone(strokes));strokes=history.length?history.pop():strokes.slice(0,-1);repaint();save();}};$('redo').onclick=()=>{if(redo.length){history.push(structuredClone(strokes));strokes=redo.pop();repaint();save();}};
function count(){return mode==='scratch'?1:mode==='pdf'?pdf.numPages:mode==='board'?lesson.boardSteps.length:lesson.slides.length;}
async function draw(){busy=true;const epoch=++renderEpoch;await saveChain;strokes=structuredClone(pendingInk.get(key())||await read('ink',key())||[]);if(epoch!==renderEpoch)return;redo=[];history=[];let h=900;
if(mode==='pdf'){const pg=await pdf.getPage(page+1);if(epoch!==renderEpoch)return;const v=pg.getViewport({scale:1}),vp=pg.getViewport({scale:1280/v.width});h=Math.ceil(vp.height);paper.height=h;ink.height=h;ctx.fillStyle='white';ctx.fillRect(0,0,1280,h);await pg.render({canvasContext:ctx,viewport:vp}).promise;$('script').textContent='教材原页 · 第 '+(page+1)+' 页（PDF页序）。笔迹按文件内容和页码保存，不会写入或修改你的原文件。';}
else if(mode==='scratch'){paper.height=h;ink.height=h;ctx.fillStyle='#fbfaf4';ctx.fillRect(0,0,1280,h);lineText('导入教材PDF，逐页阅读与手写',80,180,1100,42);}
else{paper.height=h;ink.height=h;ctx.fillStyle=mode==='board'?'#173f34':'#fbfaf4';ctx.fillRect(0,0,1280,h);if(mode==='board'){lineText(lesson.title,65,80,1150,38,'#fff');let text=lesson.boardSteps.slice(0,page+1).map(x=>x.content).join('\n\n');lineText(text,65,155,1150,30,'#f5f4cf',46);$('script').textContent=lesson.boardSteps[page].cue;}else{const s=lesson.slides[page];lineText(`${page+1} / ${count()}  ·  ${s.time}`,55,50,1170,20,'#60786a');lineText(s.title,55,105,1170,38);let y=155;for(const t of s.lines||[])y=lineText(t,65,y,1140,28,'#244a3c',42)+14;if(s.diagram){const img=new Image();await new Promise((resolve,reject)=>{img.onload=resolve;img.onerror=reject;img.src='data:image/svg+xml;charset=utf-8,'+encodeURIComponent(s.diagram)});if(epoch!==renderEpoch)return;ctx.drawImage(img,65,Math.max(290,y+5),1150,Math.min(450,850-Math.max(290,y+5)));}$('script').textContent=s.script+'\n\n学生活动：'+s.activity+'\n观察学生是否理解：'+s.evidence;}}
if(epoch!==renderEpoch)return;busy=false;repaint();$('jump-page').value=page+1;$('jump-page').max=count();$('page-label').textContent=(mode==='board'?'板书步骤 ':mode==='pdf'?'教材页 ':'课件页 ')+(page+1)+' / '+count();$('prev').disabled=page===0;$('next').disabled=page===count()-1;status('笔迹自动保存 · '+(mode==='pdf'?'本地教材':'课程版本 '+(lesson?.version||'空白页')));}
async function change(delta){if(drawing||busy)return;page=Math.max(0,Math.min(count()-1,page+delta));await draw();}
$('prev').onclick=()=>change(-1).catch(showError);$('next').onclick=()=>change(1).catch(showError);
async function switchMode(m){if(!lesson||busy||drawing)return;$('title').textContent=lesson.title;mode=m;docKey='lesson:'+lesson.id+':'+lesson.version;page=0;await draw();}
$('board').onclick=()=>switchMode('board').catch(showError);$('slides').onclick=()=>switchMode('slides').catch(showError);
async function openPDF(bytes,id,name){status('正在渲染教材…');if(busy||drawing)return;const lib=await import('./vendor/pdf.min.mjs');lib.GlobalWorkerOptions.workerSrc='./vendor/pdf.worker.min.mjs';pdf=await lib.getDocument({data:new Uint8Array(bytes),isEvalSupported:false}).promise;docKey='pdf:'+id;mode='pdf';page=0;$('title').textContent=name;await draw();}
$('pdf-open').onclick=()=>$('pdf-file').click();$('pdf-file').onchange=async e=>{const f=e.target.files[0];if(!f)return;try{if(f.size>150*1024*1024)throw Error('请导入150MB以内的PDF');const bytes=await f.arrayBuffer(),hash=Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',bytes))).map(x=>x.toString(16).padStart(2,'0')).join('');await write('docs',bookKey,{bytes,name:f.name,id:hash});await openPDF(bytes,hash,f.name);}catch(err){showError(err);}finally{e.target.value='';}};
$('saved-pdf').onclick=async()=>{try{const d=await read('docs',bookKey);if(!d)throw Error('本设备还没有导入教材PDF');await openPDF(d.bytes,d.id,d.name);}catch(e){showError(e)}};
$('export').onclick=async()=>{try{await saveChain;let all={};try{all=await new Promise((resolve,reject)=>{const tx=db.transaction('ink'),rows={};const r=tx.objectStore('ink').openCursor();r.onsuccess=()=>{const c=r.result;if(c){rows[c.key]=c.value;c.continue()}else resolve(rows)};r.onerror=()=>reject(r.error)});}catch{}for(const [k,v]of pendingInk)all[k]=v;all[key()]=structuredClone(strokes);download(new Blob([JSON.stringify({schema:1,notes:all})],{type:'application/json'}),'地理手写笔迹.json');}catch(e){showError(e)}};
$('import').onclick=()=>$('ink-file').click();$('ink-file').onchange=async e=>{try{const f=e.target.files[0];if(!f||f.size>30e6)throw Error('请选择30MB以内的笔迹备份');const data=JSON.parse(await f.text());if(data.schema!==1||!data.notes||Array.isArray(data.notes)||typeof data.notes!=='object')throw Error('笔迹格式不正确');const rows=Object.entries(data.notes);for(const [k,ss] of rows){if(!/^(lesson|pdf|scratch):/.test(k)||!Array.isArray(ss)||ss.length>20000)throw Error('笔迹内容无效');for(const s of ss){if(!['pen','highlight'].includes(s.tool)||!/^#[0-9a-f]{6}$/i.test(s.color)||!Number.isFinite(s.width)||s.width<1||s.width>40||!Array.isArray(s.points)||!s.points.length||!s.points.every(p=>['x','y','p'].every(v=>Number.isFinite(p[v])&&p[v]>=0&&p[v]<=1)))throw Error('笔迹内容无效');}}await ready;await new Promise((resolve,reject)=>{const tx=db.transaction('ink','readwrite');for(const[k,ss]of rows){const r=tx.objectStore('ink').get(k);r.onsuccess=()=>{const merged=r.result||[],set=new Set(merged.map(x=>JSON.stringify(x)));tx.objectStore('ink').put([...merged,...ss.filter(x=>!set.has(JSON.stringify(x)))],k)}}tx.oncomplete=resolve;tx.onerror=()=>reject(tx.error)});pendingInk.clear();await draw();status('笔迹已合并导入');}catch(err){showError(err)}finally{e.target.value=''}};
$('image').onclick=()=>{const c=document.createElement('canvas');c.width=1280;c.height=paper.height;const x=c.getContext('2d');x.drawImage(paper,0,0);x.drawImage(ink,0,0);c.toBlob(b=>download(b,`地理标注-${page+1}.png`));};
$('show-notes').onclick=()=>{$('notes').hidden=!$('notes').hidden;$('show-notes').textContent=$('notes').hidden?'显示教师提示':'隐藏教师提示';};
$('jump').onclick=()=>{const v=+$('jump-page').value;if(Number.isInteger(v)&&v>=1&&v<=count())change(v-1-page).catch(showError);else status('请输入有效页码');};
function showError(e){busy=false;status(e.message||'操作失败，请重试');}
try{await ready;if(topicId){const data=await fetch('./data/teaching.json').then(r=>r.json());lesson=data.lessons.find(x=>x.id===topicId);if(!lesson)throw Error('该知识点的学生课件尚未编写，请返回查看覆盖清单');docKey='lesson:'+lesson.id+':'+lesson.version;$('title').textContent=lesson.title;await draw();}else{lesson=null;$('board').disabled=$('slides').disabled=true;$('prev').disabled=$('next').disabled=true;ctx.fillStyle='#fbfaf4';ctx.fillRect(0,0,1280,900);lineText('导入教材PDF，逐页阅读与手写',80,180,1100,42);lineText('点击上方“导入教材PDF”，也可打开本设备上次的教材。',80,265,1100,30);docKey='scratch';mode='scratch';strokes=await read('ink',key())||[];repaint();status('准备就绪');}}catch(e){showError(e)}
if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js',{scope:'./'}).catch(()=>{});
