let T=null;names.readers='教材原书';names.standards='单元与课标';
const previousRender=render,previousCard=card,previousTopic=topic;
function unitHTML(u){return `<div class="box"><h3>单元：${esc(u.title)}</h3><p><strong>核心理解：</strong>${esc(u.idea)}</p><p><strong>单元总任务：</strong>${esc(u.task)}</p><p><strong>前置学习：</strong>${esc(u.before)}</p><p><strong>后续联系：</strong>${esc(u.after)}</p><h4>如何判断单元学懂了</h4>${list(u.rubric)}</div>`;}
function enhance(){if(!C||!T)return;if(!C.enhanced){for(const p of T.points){const s=C.topics.find(x=>x.id===p.sectionId);Object.assign(p,{book:s.book,stage:s.stage,stars:0,lesson:T.lessons.find(l=>l.id===p.id)||null});C.topics.push(p);}C.enhanced=true;}$('stats').innerHTML=[[T.points.length,'项知识工作清单'],[T.lessons.length,'份教学初稿'],[T.points.length-T.lessons.length,'项尚待编写'],[T.units.length,'个单元设计初稿']].map(([n,s])=>`<div class="stat"><strong>${n}</strong><span>${s}</span></div>`).join('');}
filteredTopics=function(){if(!T)return[];const term=$('search').value.trim().toLowerCase();return T.points.filter(p=>(!book||p.bookId===book)&&(!$('stage').value||p.stage===$('stage').value)&&(!$('ready').checked||p.lesson)&&(!term||[p.title,p.book,p.chapter].join(' ').toLowerCase().includes(term)));};
card=function(p){if(!p.sectionId)return previousCard(p);return `<button class="card" data-topic="${p.id}"><div class="card-top"><span>知识点 ${p.order}</span><span class="badge ${p.lesson?'':'pending'}">${p.lesson?'有教学初稿':'待编写'}</span></div><h3>${esc(p.title)}</h3><p>${esc(p.chapter)}</p><div class="card-bottom"><span>${esc(p.book)}</span><span>${p.lesson?'学生课件 · 板书 →':'查看覆盖记录 →'}</span></div></button>`;};
render=function(){if(!C||!T){$('content').textContent='正在载入课程与教材清单…';return;}enhance();if(!['lessons','readers','standards'].includes(view)){previousRender();return;}
let out='';if(view==='lessons'){const ts=filteredTopics();out=`<div class="notice">覆盖目标是教材每个知识点，不设系统推荐星级。目前为 ${T.points.length} 项拆分工作清单，${T.lessons.length} 份教学初稿；高中必修第一册已按清单逐项编写，其他内容仍待完成。原书正文、活动、阅读与图表尚未逐页核验，因此不能称为全教材已覆盖。</div>`;for(const b of C.books){const ps=ts.filter(x=>x.bookId===b.id);if(!ps.length)continue;out+=`<h3 class="chapter">${esc(b.title)}</h3><p><a href="${b.officialPortal}" target="_blank" rel="noopener">在出版社目录打开原书</a> · <a href="./studio.html?book=${b.id}">导入本册PDF并标注</a></p>`;for(const ch of b.chapters){const xs=ps.filter(x=>x.chapter===ch.title);if(!xs.length)continue;out+=`<h4>${esc(ch.title)} <small>当前显示 ${xs.length} 项 · 有稿 ${xs.filter(x=>x.lesson).length} 项</small></h4>${ch.topics.map(sid=>{const section=C.topics.find(x=>x.id===sid),sp=xs.filter(x=>x.sectionId===sid);return sp.length?`<h5>${esc(section.title)}</h5><div class="cards">${sp.map(card).join('')}</div>`:'';}).join('')}`;}}if(!ts.length)out+='<p>没有匹配项，请清除筛选。</p>';
}else if(view==='readers'){out='<div class="notice">原书通过人教社官方目录阅读。出版社校验访问来源，请在官方目录中点击“在线阅读”；直接打开具体书址可能被拦截。要在本站用笔逐页标注，请导入你自己的教材PDF，文件只保存在本设备。</div>'+C.books.filter(b=>!book||b.id===book).map(b=>`<article class="list-item"><h3>${esc(b.title)}</h3><p>${esc(b.officialTitle)}</p><p>${esc(b.verification)}</p><div class="row"><a class="primary-link" href="${b.officialPortal}" target="_blank" rel="noopener">官方原书目录 ↗</a><a href="./studio.html?book=${b.id}">本册PDF阅读与手写 →</a></div><p class="text-muted">原书与课件是两类内容；本站原创讲解不冒充教材原文。目前尚无逐页引用映射。</p></article>`).join('');
}else{out='<div class="notice">大单元通过核心理解、总任务、学习顺序与评价证据组织。当前完成高中必修第一册6个单元设计初稿，其余册的单元设计仍待编写与原书核对。</div><h3>课标版本与依据</h3>'+T.standards.map(s=>`<div class="box"><h4>${esc(s.stage)} · ${esc(s.version)}</h4><p>${esc(s.status)}</p><a href="${s.url}" target="_blank" rel="noopener">查看依据 ↗</a></div>`).join('')+T.units.map(u=>unitHTML(u)+`<p>学习顺序：${u.lessons.map(id=>`<button data-topic="${id}">${esc(T.points.find(p=>p.id===id).title)}</button>`).join(' → ')}</p>`).join('');}
$('content').innerHTML=out;$('books').innerHTML=C.books.map(b=>`<button data-book="${b.id}" class="${book===b.id?'selected':''}">${esc(b.title)}</button>`).join('');};
topic=function(id){if(!T)return;const p=T.points.find(x=>x.id===id);if(!p){const children=T.points.filter(x=>x.sectionId===id);if(children.length){modal('教材课节',`<h2>${esc(C.topics.find(x=>x.id===id)?.title)}</h2><p>本节已拆分为以下知识点；原有局部示范不代表整节覆盖。</p><div class="cards">${children.map(card).join('')}</div>`);return;}return previousTopic(id);}current=id;const l=p.lesson,b=C.books.find(x=>x.id===p.bookId);let out=`<span class="badge">${esc(b.title)} / ${esc(p.chapter)}</span><h2>${esc(p.title)}</h2><div class="row">${favoriteButton(id)}<a href="${b.officialPortal}" target="_blank" rel="noopener">出版社原书目录</a><a href="./studio.html?book=${b.id}">教材PDF手写</a></div>`;
if(!l){modal('知识点覆盖记录',out+`<div class="notice">尚未编写本知识点的学生课件与试讲。${esc(p.textbookVerification)}</div><p>原书页码：待逐页定位。目标：逐项补齐，不按推荐星级筛选。</p><details><summary>教师备课题目（不进入学生课件）</summary>${related(p.sectionId)}</details>`);return;}
const u=T.units.find(x=>x.id===l.unitId);out+=`<div class="notice">${esc(l.status)}。课时按讲解、绘图与学生活动安排为13分钟，仍需实讲校时。</div><p><a class="primary-link" href="./studio.html?topic=${id}&book=${b.id}">打开学生课件与手写板书 →</a></p><details><summary>单元位置、总任务与评价</summary>${unitHTML(u)}</details><div class="detail-grid"><div class="box"><h3>教学目标</h3>${list(l.objectives)}</div><div class="box"><h3>问题链</h3>${list(l.questionChain)}</div></div><div class="box"><h3>学生是否听懂，看什么</h3><p>${esc(l.evidence)}</p><p>区域认知、综合思维、人地协调观、地理实践力需结合任务落实，不要求每个13分钟片段平均覆盖四项；本课依据具体图示、解释与操作观察学习表现。</p></div><h3>可实际书写的板书</h3><div class="board">${esc(l.boardSteps.map(x=>x.content).join('\n'))}</div><details><summary>板书顺序与时机</summary>${list(l.boardSteps.map(x=>x.cue))}</details><h3>面向学生的讲解与活动</h3>`+l.slides.map(s=>`<section class="segment"><h3>${s.time} · ${esc(s.title)}</h3><p>${esc(s.script)}</p><small>学生活动：${esc(s.activity)}</small><p>理解证据：${esc(s.evidence)}</p></section>`).join('')+`<div class="detail-grid"><div class="box"><h3>易错点</h3>${list(l.misconceptions)}</div><div class="box"><h3>试讲亮点</h3>${list(l.highlights)}</div></div><div class="box"><h3>课标对应</h3><p>${esc(l.standard.version)} · ${esc(l.standard.module)} · 内容要求 ${esc(l.standard.clause)}</p><p>${esc(l.standard.status)}</p><a href="${l.standard.url}" target="_blank" rel="noopener">课标原文件 ↗</a></div><div class="box"><h3>来源与教材映射</h3><p>${esc(l.source)}</p></div><details><summary>教师备课题目（不进入学生课件）</summary>${related(p.sectionId)}</details><div class="box"><h3>试讲练习</h3><div class="timer"><strong id="clock">${timerTarget===id?timeText():'00:00'}</strong><button id="start-timer" data-id="${id}">开始 / 暂停</button><button id="reset-timer">重新计时</button></div><textarea id="note" aria-label="复盘笔记" placeholder="学生在哪一步听懂，哪一步仍卡住？"></textarea><label>自评 <select id="rating"><option>3</option><option>1</option><option>2</option><option>4</option><option>5</option></select></label><button id="save-practice" data-id="${id}">保存本次练习</button></div>`;modal('知识点教学设计',out);};
const oldSetView=setView;setView=function(v){oldSetView(v);$('stars').hidden=true;if(v==='readers')$('subtitle').textContent='出版社原书入口与本地教材批注，按册管理。';if(v==='standards')$('subtitle').textContent='单元核心理解、任务与证据，落实到每个课时。';};
fetch('./data/teaching.json').then(r=>{if(!r.ok)throw Error();return r.json()}).then(x=>{T=x;if(C){enhance();render();}}).catch(()=>{$('content').textContent='课程数据读取失败，请联网刷新重试。'});
