/* Inline teaching design. Book payloads load only when opened. */
const courseLoads=new Map();let requestedCourse=null;
async function fullCourse(p){if(p.lesson?.template)return p.lesson;if(!courseLoads.has(p.bookId))courseLoads.set(p.bookId,fetch(`./data/lessons-${p.bookId}.json`).then(r=>{if(!r.ok)throw Error('课程读取失败');return r.json();}).then(ls=>{for(const l of ls){const point=T.points.find(x=>x.id===l.id);if(point)point.lesson=l;}return ls;}).catch(e=>{courseLoads.delete(p.bookId);throw e;}));await courseLoads.get(p.bookId);return p.lesson;}
const libraryRender=render;let initialRoute=false;
render=function(){if(C&&T&&!initialRoute){enhance();initialRoute=true;if(location.hash.startsWith('#lesson=')){topic(decodeURIComponent(location.hash.slice(8)));return;}}if(initialRoute)history.replaceState(null,'',location.pathname+location.search);requestedCourse=null;document.body.classList.remove('lesson-open','student-view');document.body.dataset.inkKey=`view:${view}:${book}:${$('search').value}`;libraryRender();};
function field(label,html,key,extra=''){return `<section class="design-field ${extra}" data-note-anchor="${key}"><h3>${label}</h3><div>${html}</div></section>`;}
topic=async function(id){if(!T)return;const p=T.points.find(x=>x.id===id);if(!p){const first=T.points.find(x=>x.sectionId===id);if(first)return topic(first.id);return previousTopic(id);}requestedCourse=id;current=id;history.replaceState(null,'','#lesson='+encodeURIComponent(id));if($('detail').open)$('detail').close();document.body.classList.add('lesson-open');document.body.classList.remove('student-view');document.body.dataset.inkKey='lesson:'+id;$('content').innerHTML='<p>正在打开本册教学设计…</p>';window.scrollTo(0,0);
try{const l=await fullCourse(p);if(requestedCourse!==id)return;const b=C.books.find(x=>x.id===p.bookId),s=T.summaries[id],d=l.template,u=T.units.find(x=>x.id===l.unitId);
let html=`<div class="lesson-actions"><button id="back-library">← 教材目录</button><button id="student-mode">学生展示</button>${favoriteButton(id)}<span>本页可直接手写 · 设计初稿</span></div><div class="lesson-heading" data-note-anchor="title"><p>${esc(b.title)} / ${esc(p.chapter)}</p><h2>${esc(p.title)}</h2><p>教学设计 · ${l.duration}分钟活动安排 · ${esc(d.method)}</p></div><div class="teaching-layout"><article class="design-sheet">`;
html+=field('教材分析',`<p>${esc(d.textbookAnalysis)}</p><details><summary>大单元：目标、总任务与学习联系</summary>${unitHTML(u)}</details>`,'analysis','teacher-only');
html+=field('学情分析',`<p>${esc(d.studentAnalysis)}</p>`,'students','teacher-only');
html+=field('教学目标',list(d.objectives),'objectives','teacher-only');
html+=field('教学重难点',`<p><b>重点：</b>${esc(d.emphasis)}</p><p><b>难点：</b>${esc(d.difficulty)}</p>`,'difficulty','teacher-only');
html+=field('教学策略',`<p>${esc(d.strategy)}</p>`,'strategy','teacher-only');
html+='<h2 class="process-title">教学过程</h2>';
for(const st of d.stages){html+=`<section class="learning-stage"><h3>${esc(st.title)} <small>${esc(st.time)}</small></h3><div data-note-anchor="${st.id}-task"><p class="task-question">${esc(st.problem)}</p><p class="learning-material">${esc(st.material)}</p>${st.diagram?`<div class="lesson-figure">${st.diagram}</div>`:''}<p><b>学习活动：</b>${esc(st.student)}</p></div><div class="teacher-only" data-note-anchor="${st.id}-teacher"><h4>教师讲解与引导</h4><p>${esc(st.teacher)}</p></div><div class="intent teacher-only" data-note-anchor="${st.id}-intent"><b>设计意图</b><p>${esc(st.intent)}</p><p><strong>学习证据：</strong>${esc(st.evidence)}</p></div></section>`;}
html+=field('布置作业',`<p>${esc(d.homework)}</p><p class="teacher-only"><b>设计意图：</b>让学生修正课堂形成的解释，用具体证据检验是否真正理解。</p>`,'homework');
html+=field('板书设计',`<div class="chalkboard">${esc(d.board.join('\n\n'))}</div><details class="teacher-only"><summary>边讲边写的顺序</summary>${list(d.boardOrder)}</details>`,'board');
html+=`<div class="teacher-only">${field('易错点',list(l.misconceptions),'mistakes')}${field('面试亮点',list(l.highlights),'highlights')}${field('PPT建议',list(l.ppt),'ppt')}<details class="box"><summary>教师备课题目（仅供备课）</summary>${related(p.sectionId)}</details><section class="box" data-note-anchor="practice"><h3>试讲练习</h3><div class="timer"><strong id="clock">${timerTarget===id?timeText():'00:00'}</strong><button id="start-timer" data-id="${id}">开始 / 暂停</button><button id="reset-timer">重新计时</button></div><textarea id="note" aria-label="复盘笔记" placeholder="记录学生理解的困难与下次调整"></textarea><label>自评 <select id="rating"><option>3</option><option>1</option><option>2</option><option>4</option><option>5</option></select></label><button id="save-practice" data-id="${id}">保存本次练习</button></section></div></article>`;
html+=`<section class="textbook-companion teacher-only" aria-label="对应教材与知识释义"><div data-note-anchor="companion"><span class="eyebrow">与本知识点对照阅读</span><h3>教材对应内容</h3><span class="source-label">${esc(s.label)}</span><p class="book-explanation">${esc(s.text)}</p><hr><h4>原书出处</h4><p>${esc(s.sourceBook)}</p><p>${esc(s.chapter)} / ${esc(s.section)}</p><p class="text-muted">${esc(s.pageStatus)}</p><a class="primary-link" href="${s.url}" target="_blank" rel="noopener">出版社原书目录 ↗</a><p class="source-note">这里是原创释义，未转载整套教材原文。官方目录中选择本册即可阅读原书。</p></div><div class="companion-standards" data-note-anchor="standard"><h4>课标与学习证据</h4><p>${esc(l.standard.version||'现行课程标准')}</p><p>${esc(l.standard.status||'待逐条核对')}</p><p>${esc(l.evidence)}</p><a href="${l.standard.url||T.standards.find(x=>x.stage===p.stage)?.url}" target="_blank" rel="noopener">课标依据 ↗</a></div><p class="source-note">${esc(d.status)}</p></section></div>`;
$('content').innerHTML=html;document.body.dataset.inkKey='lesson:'+id;document.dispatchEvent(new Event('geo-content-ready'));
}catch(e){if(requestedCourse===id)$('content').innerHTML=`<p>本册未能载入，请联网重试。</p><button data-topic="${id}">重新打开</button><button id="back-library">返回目录</button>`;}};
document.addEventListener('click',e=>{if(e.target.closest('#back-library')){render();window.scrollTo(0,0);}if(e.target.closest('#student-mode')){const on=document.body.classList.toggle('student-view');$('student-mode').textContent=on?'教师备课':'学生展示';document.dispatchEvent(new Event('geo-content-ready'));}});
