/* Local, privacy-first video practice review. Video bytes never leave this page. */
names.video='试讲视频复盘';
const vr={file:null,url:null,durationOverride:null,recordStarted:0,markers:[],frames:[],report:null,recorder:null,stream:null,chunks:[],recognition:null,transcript:'',topicId:'',saved:readReviews()};
function readReviews(){try{const x=JSON.parse(localStorage.getItem('geo-video-reviews-v1'));return Array.isArray(x)?x:[]}catch{return[]}}
function saveReviews(){try{localStorage.setItem('geo-video-reviews-v1',JSON.stringify(vr.saved.slice(0,30)));}catch{toast('复盘文字保存失败，请立即导出报告')}}
const renderBeforeVideo=render;
render=function(){if(view==='video'){requestedCourse=null;document.body.classList.remove('lesson-open','student-view');document.body.dataset.inkKey='view:video';renderVideo();return}renderBeforeVideo()};
const setViewBeforeVideo=setView;
setView=function(v){setViewBeforeVideo(v);if(v==='video'){$('subtitle').textContent='上传或录制试讲，定位到具体时间点，形成下一次可执行的训练任务。';$('reset').hidden=true}else $('reset').hidden=false};
function renderVideo(){const topics=T?T.points:[],topicOptions=topics.map(p=>`<option value="${p.id}" ${vr.topicId===p.id?'selected':''}>${esc(p.book)} · ${esc(p.title)}</option>`).join('');$('content').innerHTML=`<section class="video-review"><div class="notice">视频只在当前浏览器中打开，不会上传到GitHub或公开保存。刷新页面后需重新选择视频；复盘报告和时间点记录保存在本设备。</div><div class="video-start"><div class="video-pick"><label class="video-drop"><span><b>选择试讲视频</b><br><small>支持浏览器能播放的 MP4、MOV、WebM 等格式</small><br><input id="practice-video-file" type="file" accept="video/*"></span></label><div class="video-recorder"><b>也可以直接录制</b><p>允许摄像头和麦克风后，在本页录制。支持的格式由当前浏览器决定。</p><div class="row"><button id="record-start">开始录制</button><button id="record-stop" disabled>结束录制</button></div><label><input id="record-transcript" type="checkbox"> 同时语音转文字</label><p class="text-muted">语音识别可能由浏览器服务处理；不勾选时视频只留在本机。</p><p id="record-status">尚未录制</p></div></div></div>${vr.file?videoWorkspace(topicOptions):'<div class="video-empty">选择或录制视频后，这里会出现播放器、时间点记录和诊断表。</div>'}${savedReviews()}</section>`;$('books').innerHTML='';if(vr.file){const v=$('practice-video');v.src=vr.url;v.addEventListener('loadedmetadata',()=>{$('video-duration').textContent=formatTime(effectiveDuration(v));$('video-size').textContent=(vr.file.size/1024/1024).toFixed(1)+' MB';});}}
function videoWorkspace(opts){return `<div class="video-workspace"><div class="video-player-card"><video id="practice-video" controls playsinline preload="metadata"></video><div class="video-meta"><span>${esc(vr.file.name)}</span><span id="video-duration">读取时长…</span><span id="video-size"></span><span class="privacy-chip">仅本机打开</span></div><div class="frame-strip" id="frame-strip">${vr.frames.map((x,i)=>`<figure><img src="${x.data}" alt="视频画面${i+1}"><figcaption>${formatTime(x.time)}</figcaption></figure>`).join('')}</div><div class="row"><button id="capture-frames">提取4个画面检查构图</button><small class="text-muted">只显示在本页，不上传</small></div><h3>时间点记录</h3><div class="marker-row"><button id="marker-time">取当前时间</button><select id="marker-type"><option>需要改进</option><option>讲清楚了</option><option>知识疑问</option><option>板书问题</option><option>教态问题</option></select><input id="marker-note" placeholder="具体发生了什么，例如：2:10定义太快"><button id="marker-add">加入</button></div><div class="marker-list">${vr.markers.length?vr.markers.map((m,i)=>`<div class="list-item row"><button data-seek="${m.time}">${formatTime(m.time)}</button><span class="badge">${esc(m.type)}</span><span>${esc(m.note)}</span><button data-delete-marker="${i}">删除</button></div>`).join(''):'<p class="text-muted">播放到需要复盘的位置，点击“取当前时间”，写下观察。</p>'}</div></div><div class="review-panel"><label><b>对应知识点</b><select id="video-topic"><option value="">暂不选择</option>${opts}</select></label><label><b>试讲文字稿</b><textarea id="video-transcript" placeholder="粘贴逐字稿，或直接录制时开启浏览器语音识别。文字越完整，表达与问题链诊断越具体。">${esc(vr.transcript)}</textarea></label><p class="text-muted">网页不能凭视频文件可靠识别全部中文内容；没有文字稿时只评价时长、画面和你的时间点记录。</p><div class="analysis-actions"><button class="primary" id="analyze-video">生成本次具体诊断</button><button id="speech-start">边录边转文字</button></div>${vr.report?reportHTML(vr.report):''}</div></div>`}
function savedReviews(){if(!vr.saved.length)return'';return `<details><summary>本设备保存的复盘 · ${vr.saved.length}</summary>${vr.saved.map((r,i)=>`<article class="list-item"><h3>${esc(r.title)}</h3><p>${esc(r.date)} · ${formatTime(r.duration)}</p><button data-old-review="${i}">查看</button><button data-delete-review="${i}">删除</button></article>`).join('')}</details>`}
function effectiveDuration(v){return Number.isFinite(v?.duration)&&v.duration>0?v.duration:vr.durationOverride}
function effectiveDuration(v){return Number.isFinite(v?.duration)&&v.duration>0?v.duration:vr.durationOverride}
function formatTime(sec){if(!Number.isFinite(sec))return'--:--';sec=Math.max(0,Math.round(sec));return `${Math.floor(sec/60)}:${String(sec%60).padStart(2,'0')}`}
function reportHTML(r){return `<section class="review-result" data-note-anchor="video-report"><h2>本次复盘</h2><div class="score-grid">${r.scores.map(s=>`<div class="review-score"><strong>${s.score==null?'—':s.score+'/5'}</strong><span>${esc(s.name)}</span></div>`).join('')}</div>${r.feedback.map(x=>`<div class="feedback-item ${x.level==='good'?'good':''}"><h4>${esc(x.title)}</h4><p>${esc(x.body)}</p><small>下一次这样改：${esc(x.action)}</small></div>`).join('')}<div class="next-practice"><b>下一次只练这三件事</b><ol>${r.next.map(x=>`<li>${esc(x)}</li>`).join('')}</ol></div><div class="analysis-actions"><button id="export-video-review">导出完整复盘</button><button id="copy-video-review">复制送评文字</button></div><p class="text-muted">知识准确性、板书动作和教态需要模型实际观看视频后再评，本次网页诊断不会假装已经看懂视频内容。</p></section>`}
function feedback(level,title,body,action){return{level,title,body,action}}
function analyze(){const v=$('practice-video'),duration=effectiveDuration(v);if(!Number.isFinite(duration)||duration<=0)return toast('视频时长尚未读取完成，请稍后再试');const text=$('video-transcript').value.trim(),compact=text.replace(/\s/g,''),minutes=duration/60,chars=[...compact].length,pace=chars&&minutes?Math.round(chars/minutes):null,questions=(text.match(/[？?]/g)||[]).length,fillers=(text.match(/嗯|呃|然后|就是|这个这个|对不对|是不是/g)||[]).length,fake=(text.match(/非常好|请坐|同学们说得很好|大家异口同声/g)||[]).length,reason=(text.match(/因为|所以|因此|导致|影响|条件|证据|说明|解释/g)||[]).length,activity=(text.match(/观察|读图|比较|绘制|讨论|归纳|判断|说明|解释/g)||[]).length,summary=(text.match(/小结|总结|回到.*问题|板书/g)||[]).length;
const f=[],scores=[];let timeScore=duration>=600&&duration<=900?5:duration>=540&&duration<=960?4:duration>=480&&duration<=1020?3:2;scores.push({name:'时间控制',score:timeScore});if(duration<600)f.push(feedback('fix','试讲偏短',`当前视频 ${formatTime(duration)}，距离10分钟下限还差 ${formatTime(600-duration)}。`,'补足最薄弱的解释环节，不用增加空泛互动；优先把第二个学习任务讲清。'));else if(duration>900)f.push(feedback('fix','试讲超时',`当前视频 ${formatTime(duration)}，超过15分钟 ${formatTime(duration-900)}。`,'删去重复表述，为导入、两个任务和总结分别设截止时间。'));else f.push(feedback('good','时间进入面试区间',`当前视频 ${formatTime(duration)}，处于10—15分钟范围。`,'下一次继续记录各环节结束时间，避免总时长合格但前松后紧。'));
if(chars>50){const paceScore=pace>=180&&pace<=280?5:pace>=150&&pace<=320?4:pace>=120&&pace<=350?3:2;scores.push({name:'表达节奏',score:paceScore});if(pace>280)f.push(feedback('fix','信息密度偏高',`按文字稿估算约 ${pace} 字/分钟。学生还要读图、思考和记录，连续讲述会显得赶。`,'从最长的一段中删掉同义重复，并在核心因果关系后留2—3秒观察时间。'));else if(pace<180)f.push(feedback('fix','表达节奏偏慢',`按文字稿估算约 ${pace} 字/分钟。`,'压缩铺垫和口头连接词，用“现象—证据—结论”三句完成一次解释。'));else f.push(feedback('good','文字稿密度适中',`估算约 ${pace} 字/分钟。`,'用时间点记录确认停顿是否落在学生真正需要思考的地方。'));const fillerRate=Math.round(fillers/Math.max(1,minutes)*10)/10;if(fillers)f.push(feedback('fix','口头填充词可减少',`检测到“然后、就是、嗯、呃”等约 ${fillers} 处，约 ${fillerRate} 次/分钟。`,'下一次只练前3分钟：每讲完一个观点停顿，不用“然后”抢接下一句。'));if(fake)f.push(feedback('fix','模拟互动需要真实反馈',`文字稿中有 ${fake} 处“非常好、请坐”等固定回应。`,'改成复述学生可能出现的具体答案，并指出其中哪条证据正确、哪处需要修正。'));const qpm=Math.round(questions/Math.max(1,minutes)*10)/10;scores.push({name:'问题链',score:questions>=2&&questions<=Math.ceil(minutes*3)?5:questions?3:1});f.push(questions?feedback(qpm>3?'fix':'good','问题数量与指向',`文字稿有 ${questions} 个问号，约 ${qpm} 个/分钟。数量不代表质量，还要检查问题能否推动下一步学习。`,qpm>3?'删掉齐答式小问题，保留2—3个需要读图和解释的主问题。':'给每个主问题写出预期学习证据，避免问完立即自答。'):feedback('fix','没有形成可见问题链','文字稿未检测到明确问句。','围绕导入情境保留三个问题：看到了什么、为什么、怎样迁移判断。'));scores.push({name:'地理解释',score:reason>=6?5:reason>=3?4:reason?3:1});if(reason<3)f.push(feedback('fix','因果与条件表达不足',`“因为、影响、条件、证据、解释”等词仅出现 ${reason} 次。`,'选择一个核心结论，补成“材料事实—作用过程—结论及适用条件”。'));else f.push(feedback('good','已有地理解释线索',`因果、条件或证据表达检测到 ${reason} 处。`,'逐一确认每个“因此”前面都有图表或材料依据。'));scores.push({name:'学生活动证据',score:activity>=5?5:activity>=3?4:activity?3:1});if(activity<3)f.push(feedback('fix','学生活动不够可观察',`读图、比较、绘制、说明等动作仅检测到 ${activity} 处。`,'把“思考一下”改成可检查的产出，例如“在图上画箭头并用一句话解释”。'));if(!summary)f.push(feedback('fix','收束环节不清晰','文字稿未检测到小结、回扣问题或板书整理。','最后60秒回到导入问题，沿板书说出结论、依据和条件。'));}else{scores.push({name:'表达节奏',score:null},{name:'问题链',score:null},{name:'地理解释',score:null},{name:'学生活动证据',score:null});f.push(feedback('fix','需要文字稿才能评价讲解内容','当前没有足够文字，网页无法判断语速、问题链和地理解释。','粘贴逐字稿后重新诊断；也可录制时开启“边录边转文字”。'));}
const bad=vr.markers.filter(m=>m.type!=='讲清楚了');if(bad.length)f.push(...bad.slice(0,3).map(m=>feedback('fix',`${formatTime(m.time)} · ${m.type}`,m.note||'已标记但未写具体表现。',`重放 ${formatTime(m.time)} 前后20秒，把问题改写为一个可观察动作，再单独重录这一段。`)));if(vr.frames.length){const dark=vr.frames.filter(x=>x.brightness<55);if(dark.length)f.push(feedback('fix','画面偏暗',`${dark.map(x=>formatTime(x.time)).join('、')} 的抽帧平均亮度较低。`,'将主光源放在面部前侧，避免只开背后的灯；重录10秒检查脸和板书是否同时可见。'));else f.push(feedback('good','抽样画面亮度可用','四个时间点未检测到明显过暗画面。','仍需人工检查板书是否被身体遮挡、视线是否自然。'));}else f.push(feedback('fix','尚未检查画面','还没有提取构图抽帧。','点击“提取4个画面检查构图”，再重新生成诊断。'));
const topicId=vr.topicId,p=T?.points.find(x=>x.id===topicId),next=[],guide=T?.summaries?.[topicId];if(guide)f.push(feedback('neutral','本课知识核对基准',guide.text,'回放核心讲解段，逐句核对概念、因果关系和适用条件；发现不一致时标记具体时间点。'));if(timeScore<5)next.push(duration<600?'把第二个学习任务补足后只重录8—13分钟段。':'按环节设闹钟，删去重复讲解后完整重录。');if(chars<=50)next.push('补充逐字稿，再检查语速、问题链和地理解释。');else if(pace>280||fillers)next.push('重录前3分钟，把语速控制在180—280字/分钟并减少填充词。');if(reason<3)next.push('选一个核心结论，用“证据—过程—结论—条件”讲完整。');if(activity<3)next.push('设计一个学生可画、可写或可说的产出，并明确检查标准。');while(next.length<3)next.push(['选择一个标记时间点，只重录前后40秒并对比。','沿板书用60秒回答导入问题。','回看四个抽帧，检查视线、站位和板书遮挡。'][next.length]);
vr.transcript=text;const r={id:crypto.randomUUID(),date:new Date().toLocaleString('zh-CN'),title:p?p.title:vr.file.name,topicId,duration,fileName:vr.file.name,metrics:{chars,pace,questions,fillers,reason,activity},scores,feedback:f,next:next.slice(0,3),markers:structuredClone(vr.markers),transcript:text,frames:vr.frames.map(x=>({time:x.time,brightness:x.brightness}))};vr.report=r;vr.saved.unshift(r);saveReviews();renderVideo();}
async function useFile(file,duration=null){if(!file||!file.type.startsWith('video/')&&file.size===0){toast('请选择视频文件');return}if(vr.url)URL.revokeObjectURL(vr.url);vr.file=file;vr.durationOverride=duration;vr.url=URL.createObjectURL(file);vr.frames=[];vr.markers=[];vr.report=null;renderVideo()}
async function captureFrames(){const v=$('practice-video');const duration=effectiveDuration(v);if(!Number.isFinite(duration)||!duration) return toast('视频尚未准备好');const wasPaused=v.paused,old=v.currentTime,canvas=document.createElement('canvas');canvas.width=320;canvas.height=180;const c=canvas.getContext('2d',{willReadFrequently:true}),out=[];for(const ratio of [.1,.35,.6,.85]){v.currentTime=Math.min(duration-.05,duration*ratio);await new Promise((res,rej)=>{const t=setTimeout(()=>rej(Error()),5000);v.addEventListener('seeked',()=>{clearTimeout(t);res()},{once:true})});c.drawImage(v,0,0,320,180);const px=c.getImageData(0,0,320,180).data;let sum=0;for(let i=0;i<px.length;i+=16)sum+=(px[i]+px[i+1]+px[i+2])/3;out.push({time:v.currentTime,brightness:sum/(px.length/16),data:canvas.toDataURL('image/jpeg',.72)});}v.currentTime=old;if(!wasPaused)v.play().catch(()=>{});vr.frames=out;renderVideo();}
async function startRecording(){const speech=$('record-transcript')?.checked;try{vr.stream=await navigator.mediaDevices.getUserMedia({video:{facingMode:'user'},audio:true});const types=['video/mp4','video/webm;codecs=vp9,opus','video/webm'];const type=types.find(MediaRecorder.isTypeSupported)||'';vr.chunks=[];vr.recordStarted=performance.now();vr.recorder=new MediaRecorder(vr.stream,type?{mimeType:type}:undefined);vr.recorder.ondataavailable=e=>{if(e.data.size)vr.chunks.push(e.data)};vr.recorder.onstop=()=>{const blob=new Blob(vr.chunks,{type:vr.recorder.mimeType||'video/webm'}),ext=blob.type.includes('mp4')?'mp4':'webm';useFile(new File([blob],`试讲录制-${Date.now()}.${ext}`,{type:blob.type}),Math.max(.1,(performance.now()-vr.recordStarted)/1000));vr.stream.getTracks().forEach(t=>t.stop());vr.stream=null};vr.recorder.start(1000);$('record-start').disabled=true;$('record-stop').disabled=false;$('record-status').textContent='正在录制…';if(speech)startSpeech();}catch{toast('未能使用摄像头或麦克风，请检查浏览器权限')}}
function startSpeech(){const SR=window.SpeechRecognition||window.webkitSpeechRecognition;if(!SR)return toast('当前浏览器不支持语音转文字，可录制后手动粘贴逐字稿');try{const r=new SR();r.lang='zh-CN';r.continuous=true;r.interimResults=true;let fixed=vr.transcript;r.onresult=e=>{let interim='';for(let i=e.resultIndex;i<e.results.length;i++){const s=e.results[i][0].transcript;if(e.results[i].isFinal)fixed+=s+'\n';else interim+=s}vr.transcript=fixed;const box=$('video-transcript');if(box)box.value=fixed+interim};r.onerror=()=>toast('语音识别中断，已保留得到的文字');r.onend=()=>{vr.transcript=$('video-transcript')?.value||vr.transcript};r.start();vr.recognition=r;toast('已开始识别麦克风中的中文');}catch{toast('语音识别未能启动')}}
function reportText(r){return `# 试讲视频复盘\n\n课程：${r.title}\n日期：${r.date}\n视频：${r.fileName}\n时长：${formatTime(r.duration)}\n\n## 分项结果\n${r.scores.map(x=>`- ${x.name}：${x.score==null?'待评价':x.score+'/5'}`).join('\n')}\n\n## 具体诊断\n${r.feedback.map(x=>`### ${x.title}\n${x.body}\n\n下一次这样改：${x.action}`).join('\n\n')}\n\n## 下一次只练三件事\n${r.next.map((x,i)=>`${i+1}. ${x}`).join('\n')}\n\n## 时间点记录\n${r.markers.map(x=>`- ${formatTime(x.time)}｜${x.type}｜${x.note}`).join('\n')||'无'}\n\n## 逐字稿\n${r.transcript||'未提供'}\n\n说明：本报告由本机规则诊断生成；知识准确性、板书动作与教态需实际观看视频后复核。`}
function exportReport(){const text=reportText(vr.report),u=URL.createObjectURL(new Blob([text],{type:'text/markdown;charset=utf-8'})),a=document.createElement('a');a.href=u;a.download='试讲视频复盘-'+new Date().toISOString().slice(0,10)+'.md';a.click();setTimeout(()=>URL.revokeObjectURL(u),1000)}
document.addEventListener('input',e=>{if(e.target.id==='video-transcript')vr.transcript=e.target.value});
document.addEventListener('change',e=>{if(e.target.id==='practice-video-file')useFile(e.target.files[0]);if(e.target.id==='video-transcript')vr.transcript=e.target.value;if(e.target.id==='video-topic')vr.topicId=e.target.value});
document.addEventListener('click',async e=>{const b=e.target.closest('button');if(!b||view!=='video')return;if(b.id==='record-start')startRecording();if(b.id==='record-stop'&&vr.recorder?.state==='recording')vr.recorder.stop();if(b.id==='speech-start')startSpeech();if(b.id==='marker-time')$('marker-time').textContent=formatTime($('practice-video').currentTime);if(b.id==='marker-add'){const time=$('practice-video').currentTime,note=$('marker-note').value.trim();if(!note)return toast('请写明这个时间点发生了什么');vr.markers.push({time,type:$('marker-type').value,note});vr.transcript=$('video-transcript').value;renderVideo()}if(b.dataset.seek!=null){$('practice-video').currentTime=+b.dataset.seek;$('practice-video').play().catch(()=>{})}if(b.dataset.deleteMarker!=null){vr.markers.splice(+b.dataset.deleteMarker,1);renderVideo()}if(b.id==='capture-frames')try{b.disabled=true;b.textContent='正在提取…';await captureFrames()}catch{toast('未能提取画面，请确认视频能正常播放')}if(b.id==='analyze-video')analyze();if(b.id==='export-video-review'&&vr.report)exportReport();if(b.id==='copy-video-review'&&vr.report){try{await navigator.clipboard.writeText(reportText(vr.report));toast('复盘文字已复制')}catch{toast('复制失败，请导出报告')}}if(b.dataset.oldReview!=null){vr.report=vr.saved[+b.dataset.oldReview];if(vr.file)renderVideo();else modal('已保存的视频复盘',reportHTML(vr.report))}if(b.dataset.deleteReview!=null){vr.saved.splice(+b.dataset.deleteReview,1);saveReviews();renderVideo()}});


